FUNNY_TICKER_WAITING_TEXTS = [
    "Finding best time…",
    "Searching for a better date…",
    "Hoping for a cancellation…",
    "Looking for a miracle…",
    "Scanning the matrix…",
    "Contacting agents…",
    "Nearly there…",
    "This won't take long…",
    "Good things come to those who wait…",
    "WORD doesn't like you today…",
    "Keep calm and carry on…",
    "Trust the process…",
    "Patience is a virtue…",
    "Almost got it…",
    "Your time is coming…",
    "Stay positive…",
    "Don't give up…",
]
